#!/bin/bash

# Current dir should be one dir up.
cd "$(dirname "${BASH_SOURCE}")/../";

function syncFiles() {
    rsync -av --exclude-from='./rsync-skip.txt' --no-perms . ~;
	echo "Sourcing bash profile...";
    source ~/.bash_profile;
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	syncFiles;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		syncFiles;
	fi;
fi;
unset syncFiles;